name: crispac_logistics
description: "Crispac Logistics Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^6.0.0

# --- FLUTTER LAUNCHER ICONS CONFIG (ROOT LEVEL, NOT UNDER FLUTTER) ---
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/hotel.png
    - assets/med.png
    - assets/regi.png
    - assets/school.png
    - assets/industrial.jpg
    - assets/forgot_password.png
    - assets/Custom Designs.png
    - assets/Corporate Suit.png
    - assets/Chef Coat.jpg
    - assets/Construction Wear.png
    - assets/Hospital Gown.png
    - assets/School Uniform.png
